### PR TITLE
Screenshot support

### PR DESCRIPTION
**Pull request by DanielSmedegaardBuus**
Hi again :)

I wasn't sure exactly how you'd prefer me to implement it, so this is my take. Let me know if you feel it's poor style compared to what's already there.

I also updated the README to mention the screenshot support, and to clean it up a bit.

It seems Sublime or perhaps jsfmt has done a bit of indenting and other stuff — sorry about that :/

### CODE REVIEW

**Comment by flyingfisher** [comment]
Thanks a lot for what you've done.
The README is much better than what I wrote, clean and clear.
The indent of js file is not important. This file is only to simplify NPM publish.
I've reviewed all your code, nice and good.
But @1275 JavascriptFormatter.ts, I think there is a bug. 
`fileName = ('00000' + (++app.screenshotsCount)).slice(-5);`
After this assignment, function param 'fileName' value is missing.
:-)

**Comment by DanielSmedegaardBuus** [comment]
Wow, how weird — there's an entire if block missing around it :D You can tell by the indentation. Very strange. I'll fix and push :)

**Comment by DanielSmedegaardBuus** [comment]
I don't know how I managed to do that — I had even deleted half a variable name :'D

Sorry :D

It's alright now :)

Thanks for accepting the pull requests :+1:

**Comment by DanielSmedegaardBuus** [comment]
By the way, what're those "lbParam" and "verificationErrors" arguments in the generated test cases? They're not used for anything?

**Comment by DanielSmedegaardBuus** [comment]
I'm asking because I'd like to add the option to override the screenshot filename when running the test... Would be helpful when you run the same test against different browsers :) Then I could put screenshots in subfolders matching the browser and platform.

**Comment by flyingfisher** [comment]
There is a project name "[loadbooster](https://www.loadbooster.com/)", which I built with another guy.
And this tool is written for that project. With that tool, user can use selenium write their cases and run it in loadbooster. Those two arguments, "lbParam" and "verificationErrors", are used in loadbooster. 
:-)

**Comment by DanielSmedegaardBuus** [comment]
Ah, cool cool :)

Would it be alright to add a fourth argument, "options", and then use that for stuff like this?

**Comment by flyingfisher** [comment]
I will think about it.

**Comment by DanielSmedegaardBuus** [comment]
Alright — I'll push a proposal in a bit, let me know what you think :) I think it'd be cool to perhaps put all extra options in a second parameter as a hash, e.g.

```
module.exports = function testCaseFunction(browser, options) {
    if (!options) options = {};
    if (!options.lbParam) options.lbParam = {vuSn: 1}
    ...
```

— but then you'd have to change your code in loadbooster as well... :/

**Comment by DanielSmedegaardBuus** [comment]
I've [pushed a fourth parameter proposal](https://github.com/DanielSmedegaardBuus/selenium-html-js-converter/commit/d472e3c20254938828e1e1f8f061c1afa7682fde). I'll push the single-options-hash proposal in a bit :)

**Pull request merged**
